const imageCache = new Map();
function getImage(asset) { if (!asset?.dataUrl) return null; if (!imageCache.has(asset.id)) { const image=new Image();image.src=asset.dataUrl;imageCache.set(asset.id,image); } return imageCache.get(asset.id); }
export function pointFromEvent(canvas,event,width,height){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*width/r.width,y:(event.clientY-r.top)*height/r.height};}
export function hitTest(scene,p){return [...scene.objects].sort((a,b)=>(b.layer||0)-(a.layer||0)).find(o=>o.visible!==false&&p.x>=o.x&&p.x<=o.x+o.width*(o.scale||1)&&p.y>=o.y&&p.y<=o.y+o.height*(o.scale||1))||null;}
export function drawScene(canvas,scene,project,selectedId=null,{grid=true,zoom=1,hud=null}={}){
 const ctx=canvas.getContext('2d'),w=project.settings.width||960,h=project.settings.height||540;canvas.width=w*zoom;canvas.height=h*zoom;ctx.setTransform(zoom,0,0,zoom,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle=project.settings.background||'#101922';ctx.fillRect(0,0,w,h);
 if(grid){ctx.strokeStyle='rgba(125,190,205,.11)';ctx.lineWidth=1;const step=project.settings.grid||32;ctx.beginPath();for(let x=0;x<=w;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=0;y<=h;y+=step){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke()}
 for(const o of [...scene.objects].sort((a,b)=>(a.layer||0)-(b.layer||0))){if(o.visible===false)continue;const ow=o.width*(o.scale||1),oh=o.height*(o.scale||1);ctx.save();ctx.globalAlpha=o.opacity??1;ctx.translate(o.x+ow/2,o.y+oh/2);ctx.rotate((o.rotation||0)*Math.PI/180);const x=-ow/2,y=-oh/2;ctx.fillStyle=o.fill||'#39dfff';ctx.strokeStyle=o.stroke||'#c8fbff';ctx.lineWidth=2;
  const asset=project.assets.find(a=>a.id===o.assetId);const image=getImage(asset);if(image?.complete&&image.naturalWidth){ctx.drawImage(image,x,y,ow,oh)}else if(o.type==='Circle'||o.type==='Coin'){ctx.beginPath();ctx.ellipse(0,0,ow/2,oh/2,0,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(o.type==='Text'||o.type==='Button'){ctx.fillRect(x,y,ow,oh);ctx.fillStyle='#06121a';ctx.font=`bold ${Math.max(12,Math.min(22,oh*.42))}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.text||o.name,0,0,ow-8)}else{ctx.fillRect(x,y,ow,oh);ctx.strokeRect(x,y,ow,oh);if(['Player','Enemy','Platform'].includes(o.type)){ctx.fillStyle='rgba(255,255,255,.78)';ctx.font='11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.name,0,0,ow-8)}}
  ctx.restore();if(o.id===selectedId){ctx.save();ctx.strokeStyle='#54f6ff';ctx.setLineDash([5,4]);ctx.lineWidth=1.5;ctx.strokeRect(o.x,o.y,ow,oh);ctx.setLineDash([]);ctx.fillStyle='#eaffff';ctx.fillRect(o.x+ow-5,o.y+oh-5,10,10);ctx.restore()}}
 if(hud){ctx.save();ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(10,10,160,34);ctx.fillStyle='#8ffaff';ctx.font='bold 16px Arial';ctx.fillText(`Score ${hud.Score??0}`,20,32);ctx.restore()}
}
