import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-auth.js';
import {getProject,saveProject,deleteProject,newId,importProject} from './project-store.js';
import {drawScene,pointFromEvent,hitTest} from './canvas.js';
import {BEHAVIORS,OBJECT_TYPES,behaviorMarkup} from './behaviors.js';
import {createEvent,eventCard} from './events.js';
import {addAsset,assetSelectOptions} from './assets.js';
import {GameRuntime} from './runtime.js';

const firebaseConfig={apiKey:'AIzaSyAHLyiX6AvIjEr-hkaBGKg_kEf78Xskd48',authDomain:'southeast-studios.firebaseapp.com',projectId:'southeast-studios',storageBucket:'southeast-studios.firebasestorage.app',messagingSenderId:'977801049293',appId:'1:977801049293:web:911d9d0986a025d113e584'};
const auth=getAuth(initializeApp(firebaseConfig));onAuthStateChanged(auth,user=>{if(!user)location.href='login.html';else document.querySelector('#userEmail').textContent=user.email||'Signed in'});
const $=s=>document.querySelector(s), id=new URLSearchParams(location.search).get('id');
let project,selectedId=null,zoom=1,grid=true,snap=true,runtime=null,history=[],future=[],autosaveTimer=null,dirty=false,tool='objects',bottomTab='events',consoleLines=[];
const canvas=$('#gameCanvas'),ctx=$('#bottomContent');
function scene(){return project.scenes.find(s=>s.id===project.activeSceneId)||project.scenes[0]}
function selected(){return scene().objects.find(o=>o.id===selectedId)||null}
function toast(message){const n=document.createElement('div');n.className='toast';n.textContent=message;$('#toastHost').append(n);setTimeout(()=>n.remove(),2600)}
function log(message){consoleLines.unshift(`${new Date().toLocaleTimeString()}  ${message}`);consoleLines=consoleLines.slice(0,60);if(bottomTab==='console')renderBottom()}
function markSaving(){dirty=true;$('#saveState').textContent='● Saving…';$('#saveState').style.color='#f6d36b';clearTimeout(autosaveTimer);autosaveTimer=setTimeout(saveNow,450)}
async function saveNow(){if(!project)return;try{project=await saveProject(project);dirty=false;$('#saveState').textContent='● Saved';$('#saveState').style.color='#8adfbd'}catch(e){$('#saveState').textContent='● Save failed';$('#saveState').style.color='#ff6d84';toast(e.message)}}
function commit(label,fn){if(runtime)return;history.push(structuredClone(project));if(history.length>80)history.shift();future=[];fn();markSaving();renderAll();log(label)}
function draw(){if(project)drawScene(canvas,scene(),project,selectedId,{grid,zoom})}
function renderScenes(){const s=$('#sceneSelect');s.innerHTML=project.scenes.map(x=>`<option value="${x.id}" ${x.id===project.activeSceneId?'selected':''}>${escapeHtml(x.name)}</option>`).join('');$('#sceneSize').textContent=`${project.settings.width} × ${project.settings.height}`}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderObjects(){const panel=$('#toolPanel');panel.innerHTML=`<div class="section-head"><span>Scene Objects · ${scene().objects.length}</span></div><div class="mini-actions"><button id="addObjectBtn" class="btn primary">＋ Add object</button></div><div id="objectList">${scene().objects.map(o=>`<div class="object-row ${o.id===selectedId?'active':''}" data-object="${o.id}"><span class="type-icon">${({Player:'◉',Sprite:'▧',Rectangle:'▰',Circle:'●',Text:'T',Platform:'▬',Enemy:'◆',Coin:'◉',Button:'▱'})[o.type]||'◇'}</span><span>${escapeHtml(o.name)}</span></div>`).join('')||'<div class="empty">Scene is empty. Add an object to start building.</div>'}</div>`;$('#addObjectBtn').onclick=()=>showModal('Add object',`<label class="field-label">Object type</label><select id="objectType">${OBJECT_TYPES.map(t=>`<option>${t}</option>`).join('')}</select>`,m=>{addObject(m.querySelector('#objectType').value);return true});panel.querySelectorAll('[data-object]').forEach(row=>row.onclick=()=>{selectedId=row.dataset.object;renderAll()})}
function renderAssetPanel(audioOnly=false){const panel=$('#toolPanel');panel.innerHTML=`<div class="section-head"><span>${audioOnly?'Audio':'Assets'}</span><span>${project.assets.filter(a=>!audioOnly||a.type==='audio').length}</span></div><label class="btn primary" style="display:block;text-align:center;cursor:pointer">＋ Upload ${audioOnly?'audio':'asset'}<input id="assetUpload" type="file" ${audioOnly?'accept="audio/mpeg,audio/wav,audio/ogg,audio/*"':'accept="image/png,image/jpeg,image/webp,image/svg+xml,audio/mpeg,audio/wav,audio/ogg"'} multiple hidden></label><p class="muted">PNG · JPG · WEBP · SVG · MP3 · WAV · OGG · max 8 MB each</p><div>${project.assets.filter(a=>!audioOnly||a.type==='audio').map(a=>`<div class="asset-row">${a.type==='image'?`<img src="${a.dataUrl}" alt="">`:'<span>♫</span>'}<span style="flex:1;overflow:hidden;text-overflow:ellipsis">${escapeHtml(a.name)}</span>${a.type==='image'&&selected()?`<button class="icon-btn" data-assign="${a.id}" title="Assign to selected sprite">↗</button>`:''}<button class="icon-btn" data-remove-asset="${a.id}" title="Remove asset">×</button></div>`).join('')||'<div class="empty">Upload an image or sound to add it to this project.</div>'}</div>`;$('#assetUpload').onchange=async e=>{for(const f of e.target.files){try{await addAsset(project,f);log(`Imported asset ${f.name}`)}catch(err){toast(err.message)}}markSaving();renderAll()};panel.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>{const o=selected();if(o)commit('Assigned sprite asset',()=>o.assetId=b.dataset.assign)});panel.querySelectorAll('[data-remove-asset]').forEach(b=>b.onclick=()=>{commit('Removed asset',()=>{project.assets=project.assets.filter(a=>a.id!==b.dataset.removeAsset);for(const s of project.scenes)for(const o of s.objects)if(o.assetId===b.dataset.removeAsset)o.assetId=''})})}
function renderTool(){if(tool==='objects')renderObjects();else if(tool==='assets')renderAssetPanel();else if(tool==='audio')renderAssetPanel(true);else if(tool==='behaviors'){const o=selected();$('#toolPanel').innerHTML=o?`<div class="section-head">Attach behaviors</div><p class="muted">${escapeHtml(o.name)}</p>${behaviorMarkup(o)}`:'<div class="empty">Select an object to add behaviors.</div>';$('#toolPanel').querySelectorAll('[data-behavior]').forEach(cb=>cb.onchange=()=>commit('Changed object behavior',()=>{o.behaviors=o.behaviors||[];o.behaviors=cb.checked?[...new Set([...o.behaviors,cb.dataset.behavior])]:o.behaviors.filter(x=>x!==cb.dataset.behavior)}))}else if(tool==='events'){bottomTab='events';renderBottom();$('#toolPanel').innerHTML='<div class="empty">Build logic rules in the Events / Logic panel below.</div>'}else if(tool==='variables'){bottomTab='variables';renderBottom();$('#toolPanel').innerHTML='<div class="empty">Edit global and scene variables in the Variables panel below.</div>'}}
function renderInspector(){const o=selected(),p=$('#inspectorPanel');if(!o){p.innerHTML='<div class="empty">Select an object to edit its properties.</div>';$('#selectionReadout').textContent='No selection';return}$('#selectionReadout').textContent=`${o.name} · ${o.type}`;p.innerHTML=`<div class="field"><label>Name</label><input data-prop="name" value="${escapeHtml(o.name)}"></div><div class="field"><label>Type</label><input value="${escapeHtml(o.type)}" disabled></div><div class="field-label">Transform</div><div class="field-grid">${[['x','X'],['y','Y'],['width','Width'],['height','Height'],['rotation','Rotation °'],['scale','Scale'],['layer','Layer']].map(([key,label])=>`<div class="field"><label>${label}</label><input data-prop="${key}" type="number" step="${key==='scale'?'.1':'1'}" value="${o[key]??0}"></div>`).join('')}</div>${o.behaviors?.some(b=>['platformer','topDown','enemyMovement'].includes(b))?`<div class="field"><label>Movement speed</label><input data-prop="speed" type="number" min="0" value="${o.speed??220}"></div>`:''}${o.behaviors?.some(b=>['gravity','physics'].includes(b))?`<div class="field"><label>Gravity</label><input data-prop="gravity" type="number" min="0" value="${o.gravity??900}"></div>`:''}${o.behaviors?.includes('health')?`<div class="field"><label>Health</label><input data-prop="health" type="number" value="${o.health??100}"></div>`:''}<div class="field-label">Appearance</div><div class="field-grid"><div class="field"><label>Color</label><input data-prop="fill" type="color" value="${/^#[0-9a-f]{6}$/i.test(o.fill||'')?o.fill:'#37d9ff'}"></div><div class="field"><label>Opacity %</label><input data-prop="opacity" type="number" min="0" max="100" value="${Math.round((o.opacity??1)*100)}"></div></div><label class="check-row"><input data-prop="visible" type="checkbox" ${o.visible!==false?'checked':''}><span>Visible in game</span></label><div class="field"><label>Image asset</label><select data-prop="assetId">${assetSelectOptions(project,o.assetId)}</select></div>${o.type==='Text'||o.type==='Button'?`<div class="field"><label>Displayed text</label><input data-prop="text" value="${escapeHtml(o.text||o.name)}"></div>`:''}<div class="field-label">Behaviors</div>${behaviorMarkup(o)}<div class="field-label" style="margin-top:12px">Object variables</div><div>${(o.variables||[]).map((v,i)=>`<div class="field-grid"><input data-object-var-name="${i}" value="${escapeHtml(v.name)}"><input data-object-var-value="${i}" value="${escapeHtml(v.value)}"><button class="icon-btn danger" data-delete-object-var="${i}">×</button></div>`).join('')}</div><button id="addObjectVar" class="btn" style="margin-top:8px">＋ Add variable</button>`;
 p.querySelectorAll('[data-prop]').forEach(input=>input.addEventListener('change',()=>{const key=input.dataset.prop;let val=input.value;if(input.type==='number')val=Number(val);if(input.type==='checkbox')val=input.checked;if(key==='opacity')val=Math.max(0,Math.min(100,val))/100;const oldName=o.name;commit(`Changed ${key}`,()=>{o[key]=val;if(key==='name')for(const ev of scene().events){if(ev.a===oldName)ev.a=val;if(ev.b===oldName)ev.b=val}})}));p.querySelectorAll('[data-behavior]').forEach(cb=>cb.onchange=()=>commit('Changed behavior',()=>{o.behaviors=o.behaviors||[];o.behaviors=cb.checked?[...new Set([...o.behaviors,cb.dataset.behavior])]:o.behaviors.filter(x=>x!==cb.dataset.behavior)}));$('#addObjectVar').onclick=()=>{const name=prompt('Variable name','Health');if(name)commit('Added object variable',()=>o.variables.push({name,value:0}))};p.querySelectorAll('[data-delete-object-var]').forEach(b=>b.onclick=()=>commit('Deleted object variable',()=>o.variables.splice(Number(b.dataset.deleteObjectVar),1)));p.querySelectorAll('[data-object-var-name]').forEach(input=>input.onchange=()=>commit('Renamed object variable',()=>o.variables[Number(input.dataset.objectVarName)].name=input.value));p.querySelectorAll('[data-object-var-value]').forEach(input=>input.onchange=()=>commit('Changed object variable',()=>o.variables[Number(input.dataset.objectVarValue)].value=input.value));}
function renderEvents(){
 ctx.innerHTML=scene().events.length?scene().events.map(e=>eventCard(e,scene(),project)).join(''):'<div class="empty">No logic yet. Add an event to make objects react during Preview.</div>';
 ctx.querySelectorAll('[data-delete-event]').forEach(button=>button.onclick=()=>{const eventId=button.closest('[data-event]').dataset.event;commit('Deleted event',()=>scene().events=scene().events.filter(event=>event.id!==eventId))});
 ctx.querySelectorAll('[data-event]').forEach(card=>{
  const event=scene().events.find(item=>item.id===card.dataset.event);
  card.querySelector('[data-event-name]').onchange=e=>commit('Renamed event',()=>event.name=e.target.value);
  card.querySelector('[data-when]').onchange=e=>commit('Changed event trigger',()=>{event.when=e.target.value;if(event.when==='health')event.target=scene().objects.find(o=>o.behaviors?.includes('health'))?.name||scene().objects[0]?.name});
  card.querySelector('[data-health-target]')?.addEventListener('change',e=>commit('Changed health condition target',()=>event.target=e.target.value));
  card.querySelector('[data-health-threshold]')?.addEventListener('change',e=>commit('Changed health threshold',()=>event.threshold=Number(e.target.value)));
  card.querySelector('[data-event-a]')?.addEventListener('change',e=>commit('Changed event object',()=>event.a=e.target.value));
  card.querySelector('[data-event-b]')?.addEventListener('change',e=>commit('Changed event object',()=>event.b=e.target.value));
  card.querySelectorAll('[data-action]').forEach(el=>el.onchange=e=>commit('Changed event action',()=>{const i=Number(e.target.dataset.action),type=e.target.value;event.actions=event.actions||[];event.actions[i]={type,target:'b',amount:type==='damage'?25:10,variable:project.variables[0]?.name||scene().variables[0]?.name||'Score',assetId:project.assets.find(a=>a.type==='audio')?.id,sceneId:project.scenes.find(s=>s.id!==scene().id)?.id}}));
  card.querySelectorAll('[data-action-amount]').forEach(el=>el.onchange=e=>commit('Changed event amount',()=>event.actions[Number(e.target.dataset.actionAmount)].amount=Number(e.target.value)));
  card.querySelectorAll('[data-action-variable]').forEach(el=>el.onchange=e=>commit('Changed event variable',()=>event.actions[Number(e.target.dataset.actionVariable)].variable=e.target.value));
  card.querySelectorAll('[data-action-asset]').forEach(el=>el.onchange=e=>commit('Changed event audio',()=>event.actions[Number(e.target.dataset.actionAsset)].assetId=e.target.value));
  card.querySelectorAll('[data-action-scene]').forEach(el=>el.onchange=e=>commit('Changed target scene',()=>event.actions[Number(e.target.dataset.actionScene)].sceneId=e.target.value));
  card.querySelectorAll('[data-delete-action]').forEach(el=>el.onclick=()=>commit('Removed event action',()=>{event.actions.splice(Number(el.dataset.deleteAction),1);if(!event.actions.length)event.actions.push({type:'destroy',target:'b'})}));
  card.querySelector('[data-add-action]').onclick=()=>commit('Added event action',()=>{event.actions=event.actions||[];event.actions.push({type:'addVariable',variable:project.variables[0]?.name||scene().variables[0]?.name||'Score',amount:10})});
 });
}
function renderVariables(){const rows=(items,scope)=>items.map((v,i)=>`<div class="variable-row"><input data-var-name="${scope}:${i}" value="${escapeHtml(v.name)}"><select data-var-type="${scope}:${i}"><option value="number" ${v.type==='number'?'selected':''}>Number</option><option value="text" ${v.type==='text'?'selected':''}>Text</option><option value="boolean" ${v.type==='boolean'?'selected':''}>Boolean</option></select><input data-var-value="${scope}:${i}" value="${escapeHtml(v.value)}"><button class="icon-btn danger" data-var-delete="${scope}:${i}">×</button></div>`).join('');ctx.innerHTML=`<div class="variables-columns"><section><h3>Global variables</h3>${rows(project.variables,'global')||'<p class="muted">No global variables.</p>'}<button class="btn" data-add-var="global">＋ Global variable</button></section><section><h3>Scene variables · ${escapeHtml(scene().name)}</h3>${rows(scene().variables,'scene')||'<p class="muted">No scene variables.</p>'}<button class="btn" data-add-var="scene">＋ Scene variable</button></section></div>`;ctx.querySelectorAll('[data-add-var]').forEach(b=>b.onclick=()=>{const name=prompt('Variable name','Score');if(name)commit('Added variable',()=>{const list=b.dataset.addVar==='global'?project.variables:scene().variables;list.push({name,type:'number',value:0})})});ctx.querySelectorAll('[data-var-name]').forEach(el=>el.onchange=()=>{const [scope,i]=el.dataset.varName.split(':');commit('Renamed variable',()=>vars(scope)[i].name=el.value)});ctx.querySelectorAll('[data-var-value]').forEach(el=>el.onchange=()=>{const [scope,i]=el.dataset.varValue.split(':');commit('Changed variable',()=>vars(scope)[i].value=el.value)});ctx.querySelectorAll('[data-var-type]').forEach(el=>el.onchange=()=>{const [scope,i]=el.dataset.varType.split(':');commit('Changed variable type',()=>vars(scope)[i].type=el.value)});ctx.querySelectorAll('[data-var-delete]').forEach(el=>el.onclick=()=>{const [scope,i]=el.dataset.varDelete.split(':');commit('Deleted variable',()=>vars(scope).splice(Number(i),1))});function vars(scope){return scope==='global'?project.variables:scene().variables}}
function renderBottom(){if(bottomTab==='events')renderEvents();else if(bottomTab==='variables')renderVariables();else ctx.innerHTML=consoleLines.map(x=>`<div class="console-line">${escapeHtml(x)}</div>`).join('')||'<div class="muted">Editor events will appear here.</div>';document.querySelectorAll('[data-bottom]').forEach(b=>b.classList.toggle('active',b.dataset.bottom===bottomTab));$('#addEvent').classList.toggle('hidden',bottomTab!=='events')}
function renderAll(){if(!project)return;$('#projectName').value=project.name;renderScenes();draw();renderTool();renderInspector();renderBottom();$('#undoBtn').disabled=!history.length;$('#redoBtn').disabled=!future.length}
function addObject(type='Sprite'){const count=scene().objects.filter(o=>o.type===type).length+1;const colors={Player:'#37d9ff',Coin:'#ffd45f',Enemy:'#ff6687',Platform:'#435b70',Text:'#e2fcff',Button:'#39dfe8'};const defaults={id:newId('object'),name:`${type} ${count}`,type,x:Math.round((project.settings.width/2-24)/project.settings.grid)*project.settings.grid,y:Math.round((project.settings.height/2-24)/project.settings.grid)*project.settings.grid,width:type==='Platform'?200:48,height:type==='Platform'?32:48,rotation:0,scale:1,visible:true,opacity:1,layer:scene().objects.length,fill:colors[type]||'#9c80ff',text:type==='Text'||type==='Button'?type:'',behaviors:type==='Player'?['topDown','collision']:[],variables:[]};commit(`Added ${type}`,()=>scene().objects.push(defaults));selectedId=defaults.id;renderAll()}
function showModal(title,content,onConfirm){const host=$('#modalHost');host.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${title}</h2>${content}<div class="modal-actions"><button class="btn" data-cancel>Cancel</button><button class="btn primary" data-confirm>Apply</button></div></div></div>`;host.querySelector('[data-cancel]').onclick=()=>host.innerHTML='';host.querySelector('[data-confirm]').onclick=()=>{if(onConfirm(host.querySelector('.modal')))host.innerHTML=''};host.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)host.innerHTML=''}}
function settingsModal(){showModal('Project settings',`<label class="field-label">Canvas width</label><input id="setWidth" type="number" min="320" max="1920" value="${project.settings.width}"><label class="field-label">Canvas height</label><input id="setHeight" type="number" min="240" max="1080" value="${project.settings.height}"><label class="field-label">Grid size</label><input id="setGrid" type="number" min="8" max="128" value="${project.settings.grid}"><label class="field-label">Background</label><input id="setBackground" type="color" value="${project.settings.background}">`,m=>{commit('Changed project settings',()=>{project.settings.width=Number(m.querySelector('#setWidth').value);project.settings.height=Number(m.querySelector('#setHeight').value);project.settings.grid=Number(m.querySelector('#setGrid').value);project.settings.background=m.querySelector('#setBackground').value});return true})}
function exportJson(){const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${project.name.replace(/[^a-z0-9_-]+/gi,'-')||'botforge-project'}.json`;a.click();URL.revokeObjectURL(a.href);toast('Project JSON exported')}
function undo(){if(!history.length)return;future.push(structuredClone(project));project=history.pop();markSaving();renderAll();toast('Undo')}
function redo(){if(!future.length)return;history.push(structuredClone(project));project=future.pop();markSaving();renderAll();toast('Redo')}
function startPreview(){if(runtime)return;saveNow();runtime=new GameRuntime(canvas,project,scene().id,()=>{runtime=null;$('#previewBtn').classList.remove('hidden');$('#stopBtn').classList.add('hidden');$('#previewBanner').classList.add('hidden');draw();renderAll();log('Preview stopped')});$('#previewBtn').classList.add('hidden');$('#stopBtn').classList.remove('hidden');$('#previewBanner').classList.remove('hidden');log('Preview started · arrows/WASD move · Space jumps')}
function stopPreview(){runtime?.stop()}
function bind(){
 $('#sceneSelect').onchange=e=>commit('Switched scene',()=>{project.activeSceneId=e.target.value;selectedId=null});$('#addScene').onclick=()=>showModal('Create scene','<label class="field-label">Scene name</label><input id="sceneName" value="New Scene">',m=>{const s={id:newId('scene'),name:m.querySelector('#sceneName').value||'New Scene',objects:[],events:[],variables:[]};commit('Created scene',()=>{project.scenes.push(s);project.activeSceneId=s.id});selectedId=null;return true});$('#renameScene').onclick=()=>showModal('Rename scene',`<label class="field-label">Scene name</label><input id="sceneName" value="${escapeHtml(scene().name)}">`,m=>{commit('Renamed scene',()=>scene().name=m.querySelector('#sceneName').value||scene().name);return true});$('#duplicateScene').onclick=()=>{const clone=structuredClone(scene());clone.id=newId('scene');clone.name=`${clone.name} Copy`;clone.objects=clone.objects.map(o=>({...o,id:newId('object')}));commit('Duplicated scene',()=>{project.scenes.push(clone);project.activeSceneId=clone.id});selectedId=null};$('#deleteScene').onclick=()=>{if(project.scenes.length<2){toast('A project must keep at least one scene');return}if(confirm(`Delete scene “${scene().name}”?`))commit('Deleted scene',()=>{project.scenes=project.scenes.filter(s=>s.id!==scene().id);project.activeSceneId=project.scenes[0].id;selectedId=null})};
 document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));renderTool()});document.querySelectorAll('[data-bottom]').forEach(b=>b.onclick=()=>{bottomTab=b.dataset.bottom;renderBottom()});$('#addEvent').onclick=()=>commit('Added event',()=>scene().events.push(createEvent()));$('#deleteObject').onclick=()=>deleteSelected();$('#duplicateObject').onclick=duplicateSelected;$('#saveBtn').onclick=saveNow;$('#signOutBtn').onclick=async()=>{await signOut(auth);location.href='login.html'};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#previewBtn').onclick=startPreview;$('#stopBtn').onclick=stopPreview;$('#settingsBtn').onclick=settingsModal;$('#exportBtn').onclick=exportJson;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=await importProject(JSON.parse(await file.text()));location.href=`botforge-editor.html?id=${encodeURIComponent(imported.id)}`}catch(err){toast(`Import failed: ${err.message}`)}e.target.value=''};
 $('#projectName').onchange=()=>commit('Renamed project',()=>project.name=$('#projectName').value.trim()||'Untitled Game');$('#gridToggle').onchange=e=>{grid=e.target.checked;draw()};$('#snapToggle').onchange=e=>snap=e.target.checked;$('#zoomSelect').onchange=e=>{zoom=Number(e.target.value);draw()};
 let drag=null;canvas.addEventListener('pointerdown',e=>{if(runtime)return;if(e.altKey||e.button===1){drag={pan:true,x:e.clientX,y:e.clientY,sl:$('#canvasWrap').scrollLeft,st:$('#canvasWrap').scrollTop};canvas.setPointerCapture(e.pointerId);return}const p=pointFromEvent(canvas,e,project.settings.width,project.settings.height),o=selected();const handle=o&&p.x>=o.x+o.width-14&&p.y>=o.y+o.height-14;const hit=hitTest(scene(),p);selectedId=hit?.id||null;if(hit){drag={id:hit.id,mode:handle?'resize':'move',startX:p.x,startY:p.y,baseX:hit.x,baseY:hit.y,baseW:hit.width,baseH:hit.height,before:structuredClone(project)};canvas.setPointerCapture(e.pointerId)}renderAll()});canvas.addEventListener('pointermove',e=>{const p=pointFromEvent(canvas,e,project.settings.width,project.settings.height);$('#coordReadout').textContent=`X ${Math.round(p.x)} · Y ${Math.round(p.y)}`;if(!drag)return;if(drag.pan){$('#canvasWrap').scrollLeft=drag.sl-(e.clientX-drag.x);$('#canvasWrap').scrollTop=drag.st-(e.clientY-drag.y);return}const o=scene().objects.find(x=>x.id===drag.id);if(!o)return;let nx=drag.baseX+(p.x-drag.startX),ny=drag.baseY+(p.y-drag.startY),nw=drag.baseW+(p.x-drag.startX),nh=drag.baseH+(p.y-drag.startY);if(snap){const g=project.settings.grid;nx=Math.round(nx/g)*g;ny=Math.round(ny/g)*g;nw=Math.round(nw/g)*g;nh=Math.round(nh/g)*g}if(drag.mode==='resize'){o.width=Math.max(8,nw);o.height=Math.max(8,nh)}else{o.x=Math.max(0,nx);o.y=Math.max(0,ny)}draw()});const endDrag=()=>{if(drag&&!drag.pan){history.push(drag.before);if(history.length>80)history.shift();future=[];markSaving();renderInspector();renderObjects();log(drag.mode==='move'?'Moved object':'Resized object')}drag=null};canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);canvas.addEventListener('dblclick',e=>{const p=pointFromEvent(canvas,e,project.settings.width,project.settings.height),o=hitTest(scene(),p);if(o){selectedId=o.id;renderAll()}});
 $('#projectName').addEventListener('input',()=>{project.name=$('#projectName').value;markSaving()});window.addEventListener('keydown',e=>{const meta=e.metaKey||e.ctrlKey,target=e.target,typing=['INPUT','TEXTAREA','SELECT'].includes(target.tagName);if(runtime){if(e.key==='Escape')stopPreview();return}if(meta&&e.key.toLowerCase()==='s'){e.preventDefault();saveNow()}else if(meta&&e.key.toLowerCase()==='z'&&!typing){e.preventDefault();e.shiftKey?redo():undo()}else if(meta&&e.key.toLowerCase()==='d'&&!typing){e.preventDefault();duplicateSelected()}else if(e.key==='Delete'||e.key==='Backspace'){if(!typing)deleteSelected()}else if(e.code==='Space'&&!typing&&!runtime){e.preventDefault();startPreview()}});
}
function deleteSelected(){if(!selected())return;const id=selectedId;commit('Deleted object',()=>scene().objects=scene().objects.filter(o=>o.id!==id));selectedId=null;renderAll()}
function duplicateSelected(){const o=selected();if(!o)return;const clone={...structuredClone(o),id:newId('object'),name:`${o.name} Copy`,x:o.x+project.settings.grid,y:o.y+project.settings.grid};commit('Duplicated object',()=>scene().objects.push(clone));selectedId=clone.id;renderAll()}
async function init(){try{project=await getProject(id);if(!project){toast('Project not found. Return to dashboard to create or import one.');$('#saveState').textContent='Project not found';return}bind();renderAll();$('#saveState').textContent='● Saved';$('#saveState').style.color='#8adfbd'}catch(e){console.error(e);toast('Could not load project')}}
init();
