import {drawScene} from './canvas.js';

const ow=o=>o.width*(o.scale||1),oh=o=>o.height*(o.scale||1);const overlaps=(a,b)=>a.x < b.x+ow(b) && a.x+ow(a) > b.x && a.y < b.y+oh(b) && a.y+oh(a) > b.y;
export class GameRuntime {
 constructor(canvas,project,sceneId,onStop){this.canvas=canvas;this.project=structuredClone(project);this.scene=this.project.scenes.find(s=>s.id===sceneId)||this.project.scenes[0];this.onStop=onStop;this.keys=new Set();this.pressed=new Set();this.edgePairs=new Set();this.last=0;this.frame=0;this.running=true;this.keydown=e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Space'].includes(e.key))e.preventDefault();if(!this.keys.has(e.key))this.pressed.add(e.key);this.keys.add(e.key)};this.keyup=e=>this.keys.delete(e.key);window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);this.canvas.tabIndex=0;this.canvas.focus();this.tick=this.tick.bind(this);this.frame=requestAnimationFrame(this.tick);}
 stop(){if(!this.running)return;this.running=false;cancelAnimationFrame(this.frame);window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);this.onStop?.()}
 tick(time){if(!this.running)return;const dt=Math.min(.04,(time-this.last)/1000||0);this.last=time;this.update(dt);drawScene(this.canvas,this.scene,this.project,null,{grid:false,hud:[...this.project.variables,...this.scene.variables].reduce((o,v)=>(o[v.name]=v.value,o),{})});this.pressed.clear();this.frame=requestAnimationFrame(this.tick)}
 update(dt){const objs=this.scene.objects;const player=objs.find(o=>o.type==='Player'||o.behaviors?.includes('platformer')||o.behaviors?.includes('topDown'));
  if(player){const speed=player.speed||220;const top=player.behaviors?.includes('topDown');const prevX=player.x,prevY=player.y;if(this.keys.has('ArrowLeft')||this.keys.has('a'))player.x-=speed*dt;if(this.keys.has('ArrowRight')||this.keys.has('d'))player.x+=speed*dt;if(top){if(this.keys.has('ArrowUp')||this.keys.has('w'))player.y-=speed*dt;if(this.keys.has('ArrowDown')||this.keys.has('s'))player.y+=speed*dt;for(const obstacle of objs){if(obstacle===player||!obstacle.behaviors?.includes('collision'))continue;if(overlaps(player,obstacle)){player.x=prevX;if(overlaps(player,obstacle))player.y=prevY}}}else{player.vy=player.vy||0;if((this.pressed.has(' ')||this.pressed.has('Space')||this.pressed.has('ArrowUp')||this.pressed.has('w'))&&player.onGround){player.vy=-440;player.onGround=false}if(player.behaviors?.includes('gravity')||player.behaviors?.includes('physics'))player.vy+=player.gravity||900;const oldBottom=player.y+oh(player);player.y+=player.vy*dt;player.onGround=false;for(const surface of objs){if(surface===player||!(surface.type==='Platform'||surface.behaviors?.includes('collision')))continue;if(overlaps(player,surface)&&player.vy>=0&&oldBottom<=surface.y+8){player.y=surface.y-oh(player);player.vy=0;player.onGround=true}}}player.x=Math.max(0,Math.min(this.project.settings.width-ow(player),player.x));player.y=Math.max(0,Math.min(this.project.settings.height-oh(player),player.y));}
  for(const body of objs.filter(o=>o!==player&&(o.behaviors?.includes('gravity')||o.behaviors?.includes('physics')))){body.vy=(body.vy||0)+(body.gravity||900)*dt;const oldBottom=body.y+oh(body);body.y+=body.vy*dt;for(const surface of objs){if(surface===body||!(surface.type==='Platform'||surface.behaviors?.includes('collision')))continue;if(overlaps(body,surface)&&body.vy>=0&&oldBottom<=surface.y+8){body.y=surface.y-oh(body);body.vy=0}}}
  for(const follower of objs.filter(o=>o.behaviors?.includes('follow')&&o!==player)){if(player){const dx=player.x-follower.x,dy=player.y-follower.y,dist=Math.hypot(dx,dy)||1;follower.x+=dx/dist*(follower.speed||90)*dt;follower.y+=dy/dist*(follower.speed||90)*dt}}
  if(player){for(const item of [...objs].filter(o=>o.behaviors?.includes('destroyOnCollision')&&o!==player)){if(overlaps(player,item))this.scene.objects=this.scene.objects.filter(o=>o!==item)}}
  for(const enemy of objs.filter(o=>o.behaviors?.includes('enemyMovement'))){enemy.direction=enemy.direction||1;enemy.x+=enemy.direction*(enemy.speed||70)*dt;if(enemy.x<0||enemy.x+enemy.width>this.project.settings.width)enemy.direction*=-1}
  for(const event of this.scene.events){if(event.when==='health'){const target=objs.find(o=>o.name===event.target);if(!target)continue;const healthKey=`${event.id}:${target.id}`;if(Number(target.health??100)<=Number(event.threshold??0)&&!this.edgePairs.has(healthKey)){this.edgePairs.add(healthKey);this.runActions(event,target,null)}continue}if(event.when==='space'&&(this.pressed.has(' ')||this.pressed.has('Space'))){this.runActions(event,player,null);continue}if(event.when!=='collision')continue;const a=objs.find(o=>o.name===event.a),b=objs.find(o=>o.name===event.b);if(!a||!b)continue;const key=`${event.id}:${a.id}:${b.id}`;const touching=overlaps(a,b);if(touching&&!this.edgePairs.has(key)){this.edgePairs.add(key);this.runActions(event,a,b)}if(!touching)this.edgePairs.delete(key)}
 }
 runActions(event,a,b){for(const action of event.actions||[]){if(action.type==='jump'){const target=a||this.scene.objects.find(o=>o.type==='Player');if(target){target.vy=-440;target.onGround=false}}else if(action.type==='destroy'){const target=action.target==='a'||!b?a:b;if(target)this.scene.objects=this.scene.objects.filter(o=>o.id!==target.id)}else if(action.type==='damage'){const target=action.target==='a'?a:(b||a);if(target){target.health=Number(target.health??100)-(Number(action.amount)||0);if(target.health<=0)this.scene.objects=this.scene.objects.filter(o=>o.id!==target.id)}}else if(action.type==='addVariable'){let v=this.scene.variables.find(x=>x.name===action.variable)||this.project.variables.find(x=>x.name===action.variable);if(!v){v={name:action.variable||'Score',type:'number',value:0};this.scene.variables.push(v)}v.value=(Number(v.value)||0)+(Number(action.amount)||0)}else if(action.type==='playAudio'){const asset=this.project.assets.find(x=>x.id===action.assetId);if(asset?.dataUrl){const audio=new Audio(asset.dataUrl);audio.play().catch(()=>{})}}else if(action.type==='switchScene'){const next=this.project.scenes.find(s=>s.id===action.sceneId);if(next)this.scene=next}}}
}
