import {newId,normalizeProject} from './project-store.js';
function obj(name,type,x,y,width,height,fill,extra={}){return{id:newId('object'),name,type,x,y,width,height,rotation:0,scale:1,visible:true,opacity:1,layer:0,fill,behaviors:[],variables:[],...extra};}
const factories={
'Empty Game':()=>({type:'2D Game',objects:[],variables:[],events:[]}),
'Platformer':()=>({type:'2D Platformer',objects:[obj('Player','Player',96,360,42,52,'#37d9ff',{behaviors:['platformer','gravity','collision'],speed:230,gravity:920}),obj('Platform','Platform',0,480,960,60,'#435b70',{behaviors:['collision']}),obj('Coin','Coin',320,420,24,24,'#ffd45f'),obj('Enemy','Enemy',540,440,38,40,'#ff6687',{behaviors:['enemyMovement','collision','health'],speed:90,health:100})],variables:[{name:'Score',type:'number',value:0},{name:'Lives',type:'number',value:3}],events:[{id:newId('event'),name:'Collect coin',when:'collision',a:'Player',b:'Coin',actions:[{type:'destroy',target:'b'},{type:'addVariable',variable:'Score',amount:10}]},{id:newId('event'),name:'Hit enemy',when:'collision',a:'Player',b:'Enemy',actions:[{type:'damage',target:'b',amount:25}]},{id:newId('event'),name:'Enemy defeated',when:'health',target:'Enemy',threshold:0,actions:[{type:'destroy',target:'a'}]}]}),
'Top Down':()=>({type:'2D Top Down',objects:[obj('Player','Player',110,110,42,42,'#37d9ff',{behaviors:['topDown','collision'],speed:220}),obj('Wall','Platform',280,150,44,260,'#435b70',{behaviors:['collision']}),obj('Coin','Coin',560,260,24,24,'#ffd45f')],variables:[{name:'Score',type:'number',value:0}],events:[{id:newId('event'),name:'Collect coin',when:'collision',a:'Player',b:'Coin',actions:[{type:'destroy',target:'b'},{type:'addVariable',variable:'Score',amount:10}]}]}),
'Space Shooter':()=>({type:'2D Shooter',objects:[obj('Player','Player',450,440,48,40,'#37d9ff',{behaviors:['topDown'],speed:260}),obj('Enemy','Enemy',450,110,42,42,'#ff6687',{behaviors:['enemyMovement'],speed:90}),obj('Bullet','Circle',470,410,12,18,'#ffe16a')],variables:[{name:'Score',type:'number',value:0},{name:'Lives',type:'number',value:3}],events:[]}),
'Endless Runner':()=>({type:'2D Runner',objects:[obj('Player','Player',130,400,42,52,'#37d9ff',{behaviors:['platformer','gravity'],speed:240,gravity:920}),obj('Ground','Platform',0,480,960,60,'#435b70'),obj('Obstacle','Enemy',520,438,36,42,'#ff6687',{behaviors:['enemyMovement']}),obj('Coin','Coin',350,390,24,24,'#ffd45f')],variables:[{name:'Score',type:'number',value:0}],events:[{id:newId('event'),name:'Collect coin',when:'collision',a:'Player',b:'Coin',actions:[{type:'destroy',target:'b'},{type:'addVariable',variable:'Score',amount:10}]}]}),
'Basic Arcade':()=>({type:'2D Arcade',objects:[obj('Player','Player',100,220,48,48,'#37d9ff',{behaviors:['topDown'],speed:240}),obj('Target','Circle',600,280,64,64,'#bb86fc'),obj('Coin','Coin',320,180,24,24,'#ffd45f')],variables:[{name:'Score',type:'number',value:0}],events:[]})};
export const templateNames=Object.keys(factories);
export function createTemplate(name,projectName=''){const data=(factories[name]||factories['Empty Game'])(),scene={id:newId('scene'),name:'Main Scene',objects:data.objects,events:data.events,variables:[]};return normalizeProject({id:newId('project'),name:projectName.trim()||(name==='Empty Game'?'Untitled Game':name),type:data.type,settings:{width:960,height:540,background:'#101922',grid:32},scenes:[scene],activeSceneId:scene.id,assets:[],variables:data.variables});}
