import {listProjects,saveProject,deleteProject,duplicateProject,formatEdited,importProject} from '../editor/project-store.js';
const $=s=>document.querySelector(s),grid=$('#projectGrid');let projects=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(s){const n=document.createElement('div');n.className='toast';n.textContent=s;document.body.append(n);setTimeout(()=>n.remove(),2300)}
function render(){$('#projectCount').textContent=`${projects.length} PROJECT${projects.length===1?'':'S'}`;const q=$('#projectSearch').value.toLowerCase(),kind=$('#typeFilter').value,order=$('#sortProjects').value;let list=projects.filter(p=>(!kind||p.type===kind)&&`${p.name} ${p.type} ${p.status}`.toLowerCase().includes(q));if(order==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(order==='oldest')list.sort((a,b)=>new Date(a.updatedAt)-new Date(b.updatedAt));if(order==='recent')list.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));grid.innerHTML=list.length?list.map(p=>`<article class="bf-project"><div class="bf-project-top"><div><span class="bf-project-type">${esc(p.type)}</span><h3>${esc(p.name)}</h3></div><details class="bf-menu"><summary aria-label="Project actions">•••</summary><div class="bf-menu-items"><button data-action="rename" data-id="${p.id}">Rename</button><button data-action="duplicate" data-id="${p.id}">Duplicate</button><button data-action="export" data-id="${p.id}">Export JSON</button><button data-action="delete" data-id="${p.id}">Delete</button></div></details></div><div class="bf-project-meta"><span class="bf-status">● ${esc(p.status)}</span><br>Edited ${formatEdited(p.updatedAt)}<br>${p.scenes.length} scene${p.scenes.length===1?'':'s'} · ${p.scenes.reduce((n,s)=>n+s.objects.length,0)} objects</div><div class="bf-project-actions"><a class="bf-btn" href="botforge-editor.html?id=${encodeURIComponent(p.id)}">Open project →</a><button class="bf-btn secondary" data-action="duplicate" data-id="${p.id}">Duplicate</button></div></article>`).join(''):'<div class="bf-empty"><h2>No projects match</h2><p>Create a game or adjust your search and filters.</p><a class="bf-btn" href="new-game.html">＋ Create New Game</a></div>';
 grid.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const p=projects.find(x=>x.id===b.dataset.id);if(!p)return;const action=b.dataset.action;if(action==='rename'){const name=prompt('Project name',p.name);if(name?.trim()){await saveProject({...p,name:name.trim()});await refresh();toast('Project renamed')}}else if(action==='duplicate'){const copy=await duplicateProject(p.id);await refresh();toast(`${copy.name} created`)}else if(action==='delete'){if(confirm(`Delete “${p.name}” permanently from this browser?`)){await deleteProject(p.id);await refresh();toast('Project deleted')}}else if(action==='export'){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.name.replace(/[^\w-]+/g,'-')}.json`;a.click();URL.revokeObjectURL(a.href)}})}
async function refresh(){projects=await listProjects();const types=[...new Set(projects.map(p=>p.type))];const current=$('#typeFilter').value;$('#typeFilter').innerHTML='<option value="">All project types</option>'+types.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');$('#typeFilter').value=types.includes(current)?current:'';render()}
$('#projectSearch').oninput=render;$('#typeFilter').onchange=render;$('#sortProjects').onchange=render;
$('#importProject').onclick=()=>$('#projectImport').click();$('#projectImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=await importProject(JSON.parse(await f.text()));await refresh();toast('Project imported');location.href=`botforge-editor.html?id=${encodeURIComponent(p.id)}`}catch(err){toast(`Import failed: ${err.message}`)}e.target.value=''};
$('#settingsButton').onclick=()=>{const saved=JSON.parse(localStorage.getItem('botforge.preferences.v1')||'{}');const host=$('#dashboardModal');host.innerHTML=`<div class="bf-modal-backdrop"><section class="bf-modal"><h2>BotForge settings</h2><p>Choose defaults for new project canvases.</p><label>Canvas width</label><input id="prefWidth" type="number" min="320" max="1920" value="${saved.width||960}"><label>Canvas height</label><input id="prefHeight" type="number" min="240" max="1080" value="${saved.height||540}"><label>Grid size</label><select id="prefGrid">${[16,24,32,48,64].map(v=>`<option ${v===(saved.grid||32)?'selected':''}>${v}</option>`).join('')}</select><div class="bf-modal-actions"><button class="bf-btn secondary" id="cancelSettings">Cancel</button><button class="bf-btn" id="saveSettings">Save settings</button></div></section></div>`;$('#cancelSettings').onclick=()=>host.innerHTML='';$('#saveSettings').onclick=()=>{localStorage.setItem('botforge.preferences.v1',JSON.stringify({width:Number($('#prefWidth').value),height:Number($('#prefHeight').value),grid:Number($('#prefGrid').value)}));host.innerHTML='';toast('Defaults saved')}};
refresh();
